### PR TITLE
Install Wget-AT as a common dependency in Docker container

### PR DESCRIPTION
**Pull request by SrihariThalla**
This PR will install Wget-AT in `/usr/local/bin/` so that all projects can use the same library.

* [ ] Also, someone on IRC told me that some dependencies are missing. Please tell me which ones.
* [x] Also, should I use the `warrior` user account as in the original Dockerfile?

### CODE REVIEW

**Comment by Freekers** [comment]
@chfoo  LGTM please :)

**Comment by chfoo** [comment]
I can't confidently pull this because I haven't been following the latest warrior development so I actually need someone testing this first, particularly ensuring that wget-at is functioning correctly. Also, I think there is a problem with the RUN commands that may not work correctly as mentioned in the docker guide https://docs.docker.com/develop/develop-images/dockerfile_best-practices/#run

**Comment by yoursunny** [comment]
This PR does not resolve #42.

```
2021-01-25 01:34:36,526 - seesaw.warrior - DEBUG - Select project google-sites
2021-01-25 01:34:36,528 - seesaw.warrior - DEBUG - Start selected project google-sites (reinstall=False)
2021-01-25 01:34:36,529 - seesaw.warrior - DEBUG - Install project google-sites
2021-01-25 01:34:36,530 - seesaw.warrior - DEBUG - git clone
2021-01-25 01:34:37,094 - seesaw.warrior - DEBUG - git operation: Cloning into '/home/warrior/projects/google-sites'...

2021-01-25 01:34:37,095 - seesaw.warrior - DEBUG - Install complete Cloning into '/home/warrior/projects/google-sites'...

2021-01-25 01:34:37,096 - seesaw.warrior - DEBUG - Result of the install process: True
2021-01-25 01:34:37,097 - seesaw.warrior - DEBUG - Clone project google-sites /home/warrior/projects/google-sites
2021-01-25 01:34:37,131 - seesaw.warrior - DEBUG - Cloning version 8b5f8fc
2021-01-25 01:34:37,148 - seesaw.warrior - DEBUG - Load pipeline /home/warrior/data/projects/google-sites-8b5f8fc/pipeline.py
2021-01-25 01:34:37,149 - seesaw.warrior - DEBUG - Pipeline has been read. Begin ConfigValue collection
2021-01-25 01:34:37,149 - seesaw.warrior - DEBUG - Executing pipeline
2021-01-25 01:34:37,560 - seesaw.warrior - ERROR - Error loading pipeline
Traceback (most recent call last):
  File "/home/warrior/src/seesaw/seesaw/warrior.py", line 736, in start_selected_project
    (project, pipeline, config_values) = self.load_pipeline(
  File "/home/warrior/src/seesaw/seesaw/warrior.py", line 686, in load_pipeline
    exec(pipeline_str, local_context, global_context)
  File "<string>", line 51, in <module>
Exception: No usable Wget+At found.
2021-01-25 01:34:37,631 - seesaw.warrior - WARNING - Project google-sites did not install correctly and we're ignoring this problem.
```

Most "grab" pipelines only look for `./wget-at` in the local directory, and do not look for the *common* `wget-at` command.
https://github.com/ArchiveTeam/google-sites-grab/blob/8b5f8fc3bf9f62ffb00fbec72d0f75708531a0d8/pipeline.py#L47

**Comment by Freekers** [comment]
> 
> 
> This PR does not resolve #42. I tried with Google Sites, GitHub, and PasteBin.
> 
> ```
> 2021-01-25 01:34:36,526 - seesaw.warrior - DEBUG - Select project google-sites
> 2021-01-25 01:34:36,528 - seesaw.warrior - DEBUG - Start selected project google-sites (reinstall=False)
> 2021-01-25 01:34:36,529 - seesaw.warrior - DEBUG - Install project google-sites
> 2021-01-25 01:34:36,530 - seesaw.warrior - DEBUG - git clone
> 2021-01-25 01:34:37,094 - seesaw.warrior - DEBUG - git operation: Cloning into '/home/warrior/projects/google-sites'...
> 
> 2021-01-25 01:34:37,095 - seesaw.warrior - DEBUG - Install complete Cloning into '/home/warrior/projects/google-sites'...
> 
> 2021-01-25 01:34:37,096 - seesaw.warrior - DEBUG - Result of the install process: True
> 2021-01-25 01:34:37,097 - seesaw.warrior - DEBUG - Clone project google-sites /home/warrior/projects/google-sites
> 2021-01-25 01:34:37,131 - seesaw.warrior - DEBUG - Cloning version 8b5f8fc
> 2021-01-25 01:34:37,148 - seesaw.warrior - DEBUG - Load pipeline /home/warrior/data/projects/google-sites-8b5f8fc/pipeline.py
> 2021-01-25 01:34:37,149 - seesaw.warrior - DEBUG - Pipeline has been read. Begin ConfigValue collection
> 2021-01-25 01:34:37,149 - seesaw.warrior - DEBUG - Executing pipeline
> 2021-01-25 01:34:37,560 - seesaw.warrior - ERROR - Error loading pipeline
> Traceback (most recent call last):
>   File "/home/warrior/src/seesaw/seesaw/warrior.py", line 736, in start_selected_project
>     (project, pipeline, config_values) = self.load_pipeline(
>   File "/home/warrior/src/seesaw/seesaw/warrior.py", line 686, in load_pipeline
>     exec(pipeline_str, local_context, global_context)
>   File "<string>", line 51, in <module>
> Exception: No usable Wget+At found.
> 2021-01-25 01:34:37,631 - seesaw.warrior - WARNING - Project google-sites did not install correctly and we're ignoring this problem.
> ```
> 
> Most "grab" pipelines only look for `./wget-at` in the local directory, and do not look for the _common_ `wget-at` command.
> https://github.com/ArchiveTeam/google-sites-grab/blob/8b5f8fc3bf9f62ffb00fbec72d0f75708531a0d8/pipeline.py#L47

Are you also facing this issue with the urlteam2 project? Because that one runs fine for me using this build.

**Comment by yoursunny** [comment]
URL Team 2 does not use wget-at, so it never had the issue in the first place.

**Comment by SrihariThalla** [comment]
Hello everyone. Thanks for the reviews. I have already created PRs in some projects to consider the w-get from this PR.

* https://github.com/ArchiveTeam/github-grab/pull/1
* https://github.com/ArchiveTeam/urls-grab/pull/3
* https://github.com/ArchiveTeam/reddit-grab/pull/5
* https://github.com/ArchiveTeam/domains-grab/pull/3

I also understand that those projects also have Dockerfiles and can be run independently.

**Comment by SrihariThalla** [comment]
Instead of building wget-at independently, how about pulling from the base Docker image maintained here?

https://github.com/ArchiveTeam/grab-base-df/blob/master/Dockerfile#L2

**Comment by SrihariThalla** [comment]
I have updated Dockerfile to download wget-at instead of building.

**Comment by km09** [comment]
Had a look through this and we can make it work - but really our best route is to rely a lot heavier on grab-base rather than throwing away all the work that's already been done there. I've got a functional version up and running for now, but requires some work in other areas. Will work on this further soon.

**Pull request merged**
