### PR TITLE
Update base-image version

### PR DESCRIPTION
**Pull request by icco**
From https://github.com/phusion/baseimage-docker/releases

### CODE REVIEW

**Comment by yipdw** [comment]
Not sure if this is a result of the change from 0.9.20 to 0.9.22, but when building the Docker image with the change in this PR, I get a "Text file busy" error when `get-wget-lua.sh` is run.  Breaking the commands up got around the error for me, i.e.

```diff
-RUN apt-get update && apt-get install -y python python-pip git pciutils sudo net-tools isc-dhcp-client python-software-properties wget libgnutls-dev liblua5.1-0 liblua5.1-0-dev autoconf flex \
- && chmod +x /get-wget-lua.sh && bash -c "/get-wget-lua.sh" \
- && apt-get remove -y libgnutls-dev liblua5.1-0-dev autoconf flex && apt-get clean && apt-get autoremove -y
+RUN apt-get update && apt-get install -y python python-pip git pciutils sudo net-tools isc-dhcp-client python-software-properties wget libgnutls-dev liblua5.1-0 liblua5.1-0-dev autoconf flex
+RUN chmod +x /get-wget-lua.sh
+RUN /get-wget-lua.sh
+RUN apt-get remove -y libgnutls-dev liblua5.1-0-dev autoconf flex && apt-get clean && apt-get autoremove -y
```

Is anyone else running into this?  If not, it might just be something strange in my Docker build environment.

**Comment by icco** [comment]
@yipdw I ran `docker build .` and had no problems. I was able to build the image and then run it and work on projects. I'm not sure if there is any way to see my progress, but I was running as user `icco`.

**Comment by icco** [comment]
(I'm using the latest version of docker for mac on osx 10.12.5)

**Comment by yipdw** [comment]
Hmm, maybe just a thing on my setup, then.  Merging.

**Pull request merged**
